package org.argogui.om;


/**
 * Maps ResultSet rows into AnaAsl objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:38 CET 2025]
 *
 */
public class AnaAslRecordMapper extends BaseAnaAslRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830838648L;



}
