package org.argogui.om;


/**
 * Tabella delle Circoscrizioni
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:26 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class AnaCircoscrizioni
    extends org.argogui.om.BaseAnaCircoscrizioni
{
    /** Serial version */
    private static final long serialVersionUID = 1739830826995L;



}
