package org.argogui.om;


/**
 * Maps ResultSet rows into AnaCircoscrizioni objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:38 CET 2025]
 *
 */
public class AnaCircoscrizioniRecordMapper extends BaseAnaCircoscrizioniRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830838652L;



}
