package org.argogui.om;


/**
 * Maps ResultSet rows into AnaNazioni objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:38 CET 2025]
 *
 */
public class AnaNazioniRecordMapper extends BaseAnaNazioniRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830838665L;



}
