package org.argogui.om;


/**
 * Maps ResultSet rows into AnaRazze objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:38 CET 2025]
 *
 */
public class AnaRazzeRecordMapper extends BaseAnaRazzeRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830838674L;



}
