package org.argogui.om;


/**
 * Maps ResultSet rows into GenHl7detail objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:38 CET 2025]
 *
 */
public class GenHl7detailRecordMapper extends BaseGenHl7detailRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830838686L;



}
