package org.argogui.om;

/**
 * log di invio dei  messaggi HL7
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:33 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class GenHl7logPeerImpl
    extends org.argogui.om.BaseGenHl7logPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1739830833521L;



}
