package org.argogui.om;


/**
 * messaggi  inviati per destinazione
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:27 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class GenHl7detail
    extends org.argogui.om.BaseGenHl7detail
{
    /** Serial version */
    private static final long serialVersionUID = 1739830827093L;



}
