package org.argogui.om;

/**
 * destinazione  dei messaggi HL7
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:33 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class GenHl7entityPeer
    extends org.argogui.om.BaseGenHl7entityPeer
{

}
