package org.argogui.om;


/**
 * Maps ResultSet rows into GenParstampe objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:38 CET 2025]
 *
 */
public class GenParstampeRecordMapper extends BaseGenParstampeRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830838694L;



}
