package org.argogui.om;

import java.sql.Connection;
import java.util.List;
import org.apache.torque.TorqueException;
import org.rigel5.db.torque.CriteriaRigel;

/**
 * Certificati utente utilizzati per identificazione.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:33 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */
public class GenSmartcardPeer
   extends org.argogui.om.BaseGenSmartcardPeer
{
  public static List<GenSmartcard> retrieveByLoginName(String loginName, Connection con)
     throws TorqueException
  {
    CriteriaRigel cr = new CriteriaRigel(TABLE_NAME);
    cr.add(LOGIN_NAME, loginName);
    return doSelect(cr, con);
  }
}
