package org.argogui.om;

/**
 * Descrittori delle stampe.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:33 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */
public class GenStampePeer
   extends org.argogui.om.BaseGenStampePeer
{
  public static GenStampe retrieveByCodice(String codiceStampa)
  {
    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  }

}
