package org.argogui.om;

/**
 * Componenti installate e rispettive versioni.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:27 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class GenVersion
   extends org.argogui.om.BaseGenVersion
{
  /** Serial version */
  private static final long serialVersionUID = 1739830827143L;

  public int compareTo(GenVersion v)
  {
    if(major > v.major)
      return 1;

    if(major < v.major)
      return -1;

    if(minor > v.minor)
      return 1;

    if(minor < v.minor)
      return -1;

    return 0;
  }

  public String format()
  {
    StringBuilder str = new StringBuilder();

    str.append("Major = ")
       .append(getMajor())
       .append("\n");
    str.append("Minor = ")
       .append(getMinor())
       .append("\n");
    str.append("StatoOper = ")
       .append(getStatoOper())
       .append("\n");
    str.append("Error = ")
       .append(getError())
       .append("\n");
    str.append("Note = ")
       .append(getNote())
       .append("\n");

    return (str.toString());
  }

}
