package org.argogui.om;

import java.sql.Connection;

/**
 * Esami richiesti per accettazione.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:27 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class InfInEsami
   extends org.argogui.om.BaseInfInEsami
{
  /** Serial version */
  private static final long serialVersionUID = 1739830827169L;

  public StpEsami getStpEsame(Connection con)
  {
    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  }

}
