package org.argogui.om;

import java.sql.Connection;

/**
 * Dati temporanei per le worklist.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:33 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */
public class RisWorklistPeer
   extends org.argogui.om.BaseRisWorklistPeer
{
  public static RisWorklist getByAccno(String AccessionNumber, Connection con)
  {
    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  }
}
