package org.argogui.om;

import org.argogui.om.utils.ou;

/**
 * Tabella delle categorie prestazioni
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:27 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class StpCategorie
   extends org.argogui.om.BaseStpCategorie
{
  /** Serial version */
  private static final long serialVersionUID = 1739830827209L;

  public boolean isAccorpamentoVisBool()
  {
    return ou.int2bool(accorpamentoVis);
  }

  public void setAccorpamentoVisBool(boolean accorpamentoVisBool)
  {
    this.accorpamentoVis = ou.bool2int(accorpamentoVisBool);
  }
}
