package org.argogui.om;


/**
 * Maps ResultSet rows into StpEsami objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:38 CET 2025]
 *
 */
public class StpEsamiRecordMapper extends BaseStpEsamiRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830838737L;



}
