package org.argogui.om;

import java.sql.Connection;
import java.util.List;
import org.rigel5.db.torque.CriteriaRigel;

/**
 * Nodi dicom
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:33 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */
public class StpNodiDicomPeer
   extends org.argogui.om.BaseStpNodiDicomPeer
{
  public static List<StpNodiDicom> getNodi(Connection con)
     throws Exception
  {
    CriteriaRigel cr = new CriteriaRigel(TABLE_NAME);
    cr.addAscendingOrderByColumn(NODI_DICOM_ID);
    return doSelect(cr, con);
  }
}
