package org.argogui.om;

/**
 * Descrittori delle aree di storage
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:33 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */
public class StpStoragePeer
   extends org.argogui.om.BaseStpStoragePeer
{
  public static final int TIPO_AREA = 0;
  public static final int TIPO_AREA_RO = 1;
  public static final int TIPO_LOCALI = 2;
  public static final int TIPO_DISTRIBUITO = 3;

}
