package org.argogui.om;

/**
 * Tabella Template Etichette. Il campo TEMPLATE, contiene text/html per il template da stampare
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:20:33 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class StpTemplateetichettePeer
    extends org.argogui.om.BaseStpTemplateetichettePeer
{

}
