package org.argogui.om;

import org.rigel5.db.torque.CriteriaRigel;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:17:28 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */
public class TurbineUserPeer
   extends org.argogui.om.BaseTurbineUserPeer
{
  public static TurbineUser getUser(int userID)
     throws Exception
  {
    return TurbineUserPeer.retrieveByPK(userID);
  }

  public static TurbineUser retriveByLoginName(String loginName)
     throws Exception
  {
    CriteriaRigel c = new CriteriaRigel();
    c.add(LOGIN_NAME, loginName);
    return getFirst(c, null);
  }
}
