package org.argogui.om;


/**
 * Maps ResultSet rows into TurbineRole objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:17:30 CET 2025]
 *
 */
public class TurbineRoleRecordMapper extends BaseTurbineRoleRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830650613L;



}
