package org.argogui.om;


/**
 * Maps ResultSet rows into TurbineUserGroupRole objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:17:30 CET 2025]
 *
 */
public class TurbineUserGroupRoleRecordMapper extends BaseTurbineUserGroupRoleRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830650627L;



}
