package org.argogui.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:17:27 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TurbinePermission
    extends org.argogui.om.BaseTurbinePermission
    implements org.apache.fulcrum.security.model.turbine.entity.TurbinePermission
{
    /** Serial version */
    private static final long serialVersionUID = 1739830647412L;



}
