package org.argogui.om;


/**
 * Maps ResultSet rows into TurbineRolePermission objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:17:30 CET 2025]
 *
 */
public class TurbineRolePermissionRecordMapper extends BaseTurbineRolePermissionRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830650622L;



}
