package org.argogui.om;


/**
 * Maps ResultSet rows into TurbineGroup objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 17 23:17:30 CET 2025]
 *
 */
public class TurbineGroupRecordMapper extends BaseTurbineGroupRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1739830650618L;



}
